<a href="https://colab.research.google.com/github/jerosam2002/my_new_ml_beginner_project/blob/main/Flower_Petal_Recognition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing Libraries....

In [ ]:
import pandas as pd
import numpy as np

Importing Datasets and printing the keys...

In [ ]:
from sklearn.datasets import load_iris
iris_dataset=load_iris()
print("Keys of dataset: \n{}".format(iris_dataset.keys()))


Keys of dataset: 
dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])


Printing the Description of the Dataset...

In [ ]:
print(iris_dataset['DESCR'][:200]+"\n...")

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive
...


Printing the Target name...

In [ ]:
print("Target names: {}".format(iris_dataset['target_names']))

Target names: ['setosa' 'versicolor' 'virginica']


Printing the Feature name...

In [ ]:
print("Feature names: {}".format(iris_dataset['feature_names']))

Feature names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


Printing the Type of data...

In [ ]:
print("Type of Data: {}".format(type(iris_dataset['data'])))

Type of Data: <class 'numpy.ndarray'>


Printing the Shape of data...

In [ ]:
print("Shape of Data: {}".format(iris_dataset['data'].shape))

Shape of Data: (150, 4)


Printing First five rows of data of the dataset...

In [ ]:
print("First five rows of data: \n{}".format(iris_dataset['data'][:5]))

First five rows of data: 
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


Printing the type of target...

In [ ]:
print("Type of target: {}".format(type(iris_dataset['target'])))

Type of target: <class 'numpy.ndarray'>


Printing the shape of target...

In [ ]:
print("Shape of target: {}".format(iris_dataset['target'].shape))

Shape of target: (150,)


Printing the Targets...

In [ ]:
print("Target: \n{}".format(iris_dataset['target']))

Target: 
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


Here we import train_test_split as the name refers it helps to split the training and test data... (normally training data 75% test data 25%).

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
                   iris_dataset['data'], iris_dataset['target'], random_state=0)

The Shapes of the training and test datas...

In [ ]:
print("X_train shape: {}".format(X_train.shape))
print("y_train shape: {}".format(y_train.shape))
print("X_test shape: {}".format(X_test.shape))
print("y_test shape: {}".format(y_test.shape))

X_train shape: (112, 4)
y_train shape: (112,)
X_test shape: (38, 4)
y_test shape: (38,)


Importing the k-nearest neighbors dictionary and introducing knn classifier...

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)

Training the knn classifier...

In [ ]:
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

Now we are making predictions...

Predictiong the shape of a wild flower...

In [ ]:
X_new=np.array([[5,2.9,1,0.2]])
print("X_new shape: {}".format(X_new.shape))

X_new shape: (1, 4)


Predicting the flower classification and printing the target name of the prediction...

In [ ]:
prediction=knn.predict(X_new)
print("Prediction: {}".format(prediction))
print("Predicted Target Name: {}".format(iris_dataset['target_names'][prediction]))

Prediction: [0]
Predicted Target Name: ['setosa']


Here we are checking the project by testing the program...

In [ ]:
y_pred=knn.predict(X_test)
print("Test set prediction:\n{}".format(y_pred))

Test set prediction:
[2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]


Printing the accuracy of the program in the testing...


In [ ]:
print("Test set score: {}".format(np.mean(y_pred==y_test)))

Test set score: 0.9736842105263158
